import test from 'node:test';
import assert from 'node:assert/strict';
import {products,sizes} from '../src/products.js';
import {filterProducts,cleanCart,changeQuantity,cartTotals,validateRegistration,readJSON,passwordHash} from '../src/domain.js';
const line=(quantity=1,size='M')=>({id:'everyday-tee',quantity,size});
const registration={name:'Demo Student',email:' Student@Example.test ',password:'test-only-123',confirm:'test-only-123'};
test('18 unique clothing products in three categories',()=>{assert.equal(products.length,18);assert.equal(new Set(products.map(p=>p.id)).size,18);assert.equal(new Set(products.map(p=>p.category)).size,3);});
test('all products offer explicit clothing sizes',()=>assert.ok(products.every(p=>p.sizes.join()===sizes.join())));
test('case insensitive trimmed search',()=>assert.equal(filterProducts(' HEAVYWEIGHT TEE ')[0].id,'everyday-tee'));
test('search and category combine',()=>{assert.equal(filterProducts('tee','Jackets').length,0);assert.equal(filterProducts('tee','T-shirts').length,5);});
test('each category contains six products',()=>{for(const c of ['T-shirts','Hoodies','Jackets'])assert.equal(filterProducts('',c).length,6);});
test('unknown search is empty',()=>assert.deepEqual(filterProducts('zzzzzzz'),[]));
test('price sort is numeric',()=>{const p=filterProducts('','All','price-low');assert.ok(p.every((v,i)=>!i||v.price>=p[i-1].price));});
test('price descending sort',()=>{const p=filterProducts('','All','price-high');assert.ok(p.every((v,i)=>!i||v.price<=p[i-1].price));});
test('null and malformed cart rejected',()=>{assert.deepEqual(cleanCart(null),[]);assert.deepEqual(cleanCart([null,{},line(-2)]),[]);});
test('unknown product and missing size ignored',()=>assert.deepEqual(cleanCart([{id:'missing',quantity:1,size:'M'},{id:'everyday-tee',quantity:1}]),[]));
test('duplicate product and size lines merge',()=>assert.deepEqual(cleanCart([line(2),line(3)]),[line(5)]));
test('different sizes remain separate',()=>assert.deepEqual(cleanCart([line(2,'M'),line(3,'L')]),[line(2,'M'),line(3,'L')]));
test('stock clamp is per size',()=>assert.deepEqual(cleanCart([line(8),line(8),line(3,'L')]),[line(10),line(3,'L')]));
test('quantity updates one size only',()=>assert.deepEqual(changeQuantity([line(1),line(1,'L')],'everyday-tee',2,'M'),[line(2),line(1,'L')]));
test('removing one size preserves the other',()=>assert.deepEqual(changeQuantity([line(1),line(1,'L')],'everyday-tee',0,'M'),[line(1,'L')]));
test('invalid or omitted size rejected',()=>{assert.throws(()=>changeQuantity([],'everyday-tee',1));assert.throws(()=>changeQuantity([],'everyday-tee',1,'XXXL'));});
test('negative fractional and excessive quantity rejected',()=>{for(const q of [-1,1.5,11,NaN])assert.throws(()=>changeQuantity([],'everyday-tee',q,'M'));});
test('out of stock clothing cannot be added',()=>assert.throws(()=>changeQuantity([],'studio-hoodie',1,'M')));
test('integer cent totals and delivery',()=>assert.deepEqual(cartTotals([line()]),{subtotal:1800,shipping:290,total:2090,count:1}));
test('free delivery above 35 euros and size-aware count',()=>assert.deepEqual(cartTotals([line(1),line(1,'L')]),{subtotal:3600,shipping:0,total:3600,count:2}));
test('empty cart totals are zero',()=>assert.deepEqual(cartTotals([]),{subtotal:0,shipping:0,total:0,count:0}));
test('valid demo registration',()=>assert.deepEqual(validateRegistration(registration),{}));
test('duplicate email is case insensitive',()=>assert.ok(validateRegistration(registration,[{email:'student@example.test'}]).email));
test('registration errors for name email password and confirmation',()=>assert.deepEqual(Object.keys(validateRegistration({name:'',email:'x',password:'1',confirm:'2'})).sort(),['confirm','email','name','password']));
test('password hashes are salted repeatable and not plaintext',async()=>{const a=await passwordHash('test-only-123','salt-a');assert.equal(a,await passwordHash('test-only-123','salt-a'));assert.notEqual(a,await passwordHash('test-only-123','salt-b'));assert.notEqual(a,await passwordHash('wrong','salt-a'));assert.equal(a.length,64);});
test('corrupt browser storage falls back',()=>assert.deepEqual(readJSON({getItem:()=>'{broken'},'cart',[]),[]));
test('blocked browser storage falls back',()=>assert.deepEqual(readJSON({getItem:()=>{throw new Error('Blocked');}},'cart',[]),[]));
