import React, {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {products,categories,findProduct} from './products.js';
import {money,normalEmail,filterProducts,cleanCart,changeQuantity,cartTotals,validateRegistration,readJSON,passwordHash} from './domain.js';
import Art from './ClothingArt.jsx';
import ProductDetail from './ProductDetail.jsx';
import {bindMenuEscape} from './navigation.js';
import './style.css';

// Legacy internal storage keys preserve existing demo accounts and carts after the brand rename.
const keys={cart:'campuscart.clothing.cart.v1',accounts:'campuscart.accounts.v1',session:'campuscart.session.v1'};
function load(key,fallback,session=false){try{return readJSON(session?sessionStorage:localStorage,key,fallback);}catch{return fallback;}}
function accounts(){const a=load(keys.accounts,[]);return Array.isArray(a)?a.filter(x=>x&&typeof x.id==='string'&&typeof x.email==='string'&&typeof x.hash==='string'&&typeof x.salt==='string'):[];}
function sessionUser(){const id=load(keys.session,null,true);const a=accounts().find(x=>x.id===id);return a?{id:a.id,name:a.name,email:a.email}:null;}
function go(path){window.location.hash=path;}
function locationInfo(){const s=(window.location.hash.slice(1)||'/').split('?');return {path:s[0],params:new URLSearchParams(s[1]||'')};}
function Icon({kind='arrow',size=22}){const paths={arrow:<path d="M5 12h14m-5-5 5 5-5 5"/>,cart:<><path d="M3 3h2l3 12h10l3-9H6"/><circle cx="9" cy="20" r="1"/><circle cx="18" cy="20" r="1"/></>,user:<><circle cx="12" cy="8" r="4"/><path d="M4 22v-3a8 8 0 0 1 16 0v3"/></>,check:<path d="m5 12 4 4L19 6"/>,search:<><circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/></>,menu:<path d="M4 6h16M4 12h16M4 18h16"/>};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[kind]||paths.arrow}</svg>;}
function Field({name,label,errors={},type='text',...props}){return <label className="field" htmlFor={name}><span>{label}</span><input id={name} name={name} type={type} aria-invalid={!!errors[name]} aria-describedby={errors[name]?`${name}-error`:undefined} {...props}/>{errors[name]&&<span className="field-error" id={`${name}-error`}>{errors[name]}</span>}</label>;}
function Empty({title,children}){return <section className="empty"><span className="empty-mark"><Icon kind="cart" size={36}/></span><h1>{title}</h1><p>{children}</p><a className="btn" href="#/products">Explore clothing <Icon/></a></section>;}
function App(){
  const [route,setRoute]=useState(locationInfo),[cart,setCart]=useState(()=>cleanCart(load(keys.cart,[]))),[user,setUser]=useState(sessionUser),[menu,setMenu]=useState(false),[notice,setNotice]=useState(''),[storageError,setStorageError]=useState('');
  const mainRef=useRef(null), firstRender=useRef(true),totals=cartTotals(cart);
  function save(key,value,session=false){try{(session?sessionStorage:localStorage).setItem(key,JSON.stringify(value));return true;}catch{setStorageError('Browser storage is unavailable or full. Allow local storage to save accounts, carts and demo orders.');return false;}}
  useEffect(()=>{const change=()=>{setRoute(locationInfo());setMenu(false);};window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
  useEffect(()=>{if(!menu)return;return bindMenuEscape(window,()=>setMenu(false),()=>document.querySelector('.menu-toggle')?.focus());},[menu]);
  useEffect(()=>{window.scrollTo(0,0);if(firstRender.current){firstRender.current=false;}else mainRef.current?.focus();document.title=`${route.path==='/'?'Campus ready':route.path.split('/')[1]||'Store'} | Wearlane`;},[route]);
  useEffect(()=>{save(keys.cart,cart);},[cart]);
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(timer);},[notice]);
  useEffect(()=>{const sync=e=>{if(e.key===keys.cart)setCart(cleanCart(load(keys.cart,[])));if(e.key===keys.accounts)setUser(sessionUser());};window.addEventListener('storage',sync);return()=>window.removeEventListener('storage',sync);},[]);
  function add(id,size){const product=findProduct(id),qty=cart.find(l=>l.id===id&&l.size===size)?.quantity||0;try{setCart(changeQuantity(cart,id,qty+1,size));setNotice(`${product.name} added to your cart.`);}catch(e){setNotice(e.message);}}
  function quantity(id,value,size){try{setCart(changeQuantity(cart,id,value,size));}catch(e){setNotice(e.message);}}
  function logout(){if(!save(keys.session,null,true))return;setUser(null);setNotice('You are signed out. Your cart is saved.');go('/');}
  function signedIn(a){if(!save(keys.session,a.id,true))throw new Error('Unable to save your session.');setUser({id:a.id,name:a.name,email:a.email});}
  function ProductCard({p}){return <article className="product-card"><a className="product-visual" href={`#/products/${p.id}`} aria-label={`View ${p.name}`}><Art product={p}/>{!p.stock&&<span className="badge">Sold out</span>}</a><div className="product-meta"><span className="eyebrow">{p.category}</span><h3><a href={`#/products/${p.id}`}>{p.name}</a></h3><div className="price-row"><strong>{money(p.price)}</strong><a className="add-button" aria-label={`Choose size for ${p.name}`} href={`#/products/${p.id}`}><span>View fit</span> ↗</a></div></div></article>;}
  function Summary({action}){return <aside className="summary"><h2>Your summary</h2><dl><div><dt>Subtotal ({totals.count} items)</dt><dd>{money(totals.subtotal)}</dd></div><div><dt>Demo delivery</dt><dd>{totals.shipping?money(totals.shipping):'Free'}</dd></div><div className="total"><dt>Total</dt><dd>{money(totals.total)}</dd></div></dl><p className="muted">Delivery is €2.90, free from €35. All displayed prices are demo prices.</p>{action}<p className="safe-note"><Icon kind="check" size={16}/> Sprint 1. Checkout planned for Sprint 2.</p></aside>;}
  let page;
  if(route.path==='/') page=<><section className="hero"><div className="hero-copy"><span className="eyebrow"><span className="dot"/> THE EVERYDAY CAMPUS COLLECTION</span><h1>Good clothes.<br/>Great campus days.</h1><p>Easy tees, comfort-first hoodies and go-anywhere layers. A considered wardrobe for your everyday campus life.</p><a className="btn" href="#/products">Find your next fit <Icon/></a><div className="hero-note"><span>01 / 03</span><span>Wear. Repeat. Make it yours.</span></div></div><div className="hero-photo"><img src={`${import.meta.env.BASE_URL}images/wearlane-models.webp`} alt="Two adult models wearing a sage tee and a cream layer over a terracotta tee — AI-generated Wearlane styling image" fetchPriority="high" width="1122" height="1402"/><span className="photo-caption">THE EVERYDAY EDIT · WEARLANE</span></div></section><div className="benefits"><span>↗ Made for your campus routine</span><span>◇ Everyday styles from €15</span><span>✓ Free demo delivery from €35</span></div><section className="section"><div className="section-heading"><div><span className="eyebrow">A PLACE FOR EVERYTHING</span><h2>What’s on your list?</h2></div><p>Three collections. One less thing to think about.</p></div><div className="category-grid">{categories.map((c,i)=><a className={`category-tile ${['sage','lilac','peach'][i]}`} href={`#/products?category=${c}`} key={c}><span className="eyebrow">0{i+1}</span><h3>{c}</h3><p>{['The foundation of a good fit.','Comfort, with room to move.','Your new everyday layer.'][i]}</p><Icon/></a>)}</div></section><section className="section"><div className="section-heading"><div><span className="eyebrow">THE SHORTLIST</span><h2>Everyday favourites</h2></div><a className="text-link" href="#/products">Shop all essentials <Icon/></a></div><div className="product-grid">{products.filter(p=>p.featured).map(p=><ProductCard key={p.id} p={p}/>)}</div></section><section className="closing-note"><span className="eyebrow">LESS FUSS. MORE FOCUS.</span><h2>Less outfit thinking.<br/>More living.</h2><a href="#/products" className="btn light">Explore the collection <Icon/></a></section></>;
  else if(route.path==='/products') page=<Catalog key={route.params.toString()} params={route.params} ProductCard={ProductCard}/>;
  else if(route.path.startsWith('/products/')) {const p=findProduct(route.path.slice('/products/'.length));page=p?<ProductDetail key={p.id} product={p} add={add}/>:<Empty title="Product not found">That style is not in our collection. Try another one.</Empty>;}
  else if(route.path==='/cart')page=!cart.length?<Empty title="A little room for essentials">Your cart is empty. Start with something for your next campus day.</Empty>:<section className="section"><span className="eyebrow">YOUR EVERYDAY PICKS</span><h1>Your cart <span className="count-label">{totals.count}</span></h1><div className="checkout-grid"><div>{cart.map(l=>{const p=findProduct(l.id);return <article className="cart-line" key={`${p.id}:${l.size}`}><a href={`#/products/${p.id}`} aria-label={`View ${p.name}`}><Art product={p}/></a><div><span className="eyebrow">{p.category}</span><h3><a href={`#/products/${p.id}`}>{p.name}</a></h3><p>Size {l.size} · {money(p.price)} each</p><div className="quantity"><button aria-label={`Decrease ${p.name} ${l.size} quantity`} onClick={()=>quantity(p.id,l.quantity-1,l.size)}>−</button><span aria-label={`${p.name} ${l.size} quantity`}>{l.quantity}</span><button disabled={l.quantity>=p.stock} aria-label={`Increase ${p.name} ${l.size} quantity`} onClick={()=>quantity(p.id,l.quantity+1,l.size)}>+</button></div><button className="remove" onClick={()=>quantity(p.id,0,l.size)}>Remove {p.name} ({l.size})</button></div><strong>{money(p.price*l.quantity)}</strong></article>})}<a className="text-link" href="#/products">← Continue browsing</a></div><Summary action={<div className="demo-note">Sprint 1 ends at the cart. Checkout, simulated payment and order confirmation are planned for Sprint 2.</div>}/></div></section>;
  else if(['/login','/register'].includes(route.path))page=<Auth key={route.path+route.params.toString()} register={route.path==='/register'} returnTo="/products" user={user} save={save} signedIn={signedIn} notify={setNotice}/>;
  else page=<Empty title="This page took a wrong turn">Use the navigation to return to your campus essentials.</Empty>;
  return <><a className="skip-link" href="#main" onClick={e=>{e.preventDefault();mainRef.current?.focus();}}>Skip to content</a><div className="demo-bar">SPRINT 1 · CLOTHING STORE DEMO <span>· Fictional details only. No real payments.</span></div><header><div className="header-inner"><a href="#/" className="brand" aria-label="Wearlane home"><span className="brand-symbol">w</span>wear<span>lane</span></a><button className="menu-toggle" aria-label="Toggle navigation" aria-expanded={menu} aria-controls="main-nav" onClick={()=>setMenu(!menu)}><Icon kind="menu"/></button><nav id="main-nav" className={menu?'open':''} aria-label="Main navigation"><a aria-current={route.path==='/'?'page':undefined} href="#/">Home</a><a aria-current={route.path.startsWith('/products')?'page':undefined} href="#/products">Shop essentials</a>{user?<button onClick={logout}>Sign out</button>:<a href="#/login">Sign in</a>}</nav><a href="#/cart" className="cart-link" aria-label={`Cart, ${totals.count} items`}><Icon kind="cart"/><span className="cart-word">Cart</span><b>{totals.count}</b></a></div></header>{storageError&&<div role="alert" className="error-banner">{storageError}</div>}<main id="main" ref={mainRef} tabIndex="-1">{page}</main><footer><div><a href="#/" className="footer-brand">wearlane ↗</a><p>Everyday clothes. Your own way.</p><p className="image-disclosure">AI-generated demo imagery. Fictional products and models.</p></div><div><b>A student-built demonstration</b><p>Group 1 · IT Agile Development<br/>Sprint 1 · Clothing store demo</p></div><div><a href="#/products">Explore the collection</a><p>Checkout is planned for Sprint 2.</p></div></footer><div className={`toast ${notice?'visible':''}`} role="status" aria-live="polite">{notice}</div></>;
}
function Catalog({params,ProductCard}){const [query,setQuery]=useState(''),[category,setCategory]=useState(categories.includes(params.get('category'))?params.get('category'):'All'),[sort,setSort]=useState('featured');const items=filterProducts(query,category,sort);return <section className="section catalog"><span className="eyebrow">THE CAMPUS COLLECTION</span><h1>Your everyday rotation.</h1><p className="intro">Tees, hoodies and layers. Good fits for whatever’s next.</p><div className="filters"><label className="search"><Icon kind="search"/><input aria-label="Search products" placeholder="Search tees, hoodies, jackets…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="sort-label">Sort by <select aria-label="Sort products" value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option><option value="name">Name: A to Z</option></select></label></div><div className="catalog-meta"><div className="pills" aria-label="Product categories">{['All',...categories].map(c=><button key={c} className={category===c?'active':''} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div><span role="status">{items.length} styles</span></div>{items.length?<div className="product-grid">{items.map(p=><ProductCard key={p.id} p={p}/>)}</div>:<div className="empty"><h2>No styles found</h2><p>Try a different search or category.</p><button className="btn" onClick={()=>{setQuery('');setCategory('All');}}>Clear filters</button></div>}</section>;}
function Auth({register,returnTo,user,save,signedIn,notify}){const [errors,setErrors]=useState({}),[busy,setBusy]=useState(false);const lock=useRef(false);async function submit(e){e.preventDefault();if(lock.current)return;const data=Object.fromEntries(new FormData(e.currentTarget));const list=accounts(),err=register?validateRegistration(data,list):{};if(Object.keys(err).length){setErrors(err);return;}lock.current=true;setBusy(true);setErrors({});try{let a;if(register){const salt=crypto.randomUUID();a={id:crypto.randomUUID(),name:data.name.trim(),email:normalEmail(data.email),salt,hash:await passwordHash(data.password,salt)};const latest=accounts();if(latest.some(x=>x.email===a.email))throw new Error('This email is already registered.');if(!save(keys.accounts,[...latest,a]))throw new Error('Could not save account. Please enable browser storage.');}else{a=list.find(x=>x.email===normalEmail(data.email));if(!a||await passwordHash(data.password,a.salt)!==a.hash)throw new Error('Email or password is incorrect. Please try again.');}signedIn(a);notify(register?'Demo account created. You are signed in.':'Welcome back. You are signed in.');go(returnTo);}catch(error){setErrors({form:error.message||'Unable to sign in. Try again.'});}finally{setBusy(false);lock.current=false;}}return user?<section className="empty"><h1>You’re signed in, {user.name}.</h1><p>Your demo account is ready.</p><a className="btn" href={`#${returnTo}`}>Continue <Icon/></a></section>:<section className="auth-grid"><div className="auth-intro"><span className="eyebrow">YOUR CAMPUS COMPANION</span><h1>{register?'A fresh start.':'Welcome back.'}</h1><p>One little account.<br/>Your everyday wardrobe.</p><Art product={products[12]}/></div><div className="auth-form"><h2>{register?'Create your demo account':'Sign in to Wearlane'}</h2><p className="demo-note">Learning demo only. Use a fictional email and a unique test password. Accounts stay in this browser; this is not production authentication.</p><form onSubmit={submit} noValidate>{errors.form&&<p role="alert" className="form-error">{errors.form}</p>}{register&&<Field name="name" label="Display name" errors={errors} maxLength={60} autoComplete="off"/>}<Field name="email" label="Demo email" type="email" errors={errors} autoComplete="off" placeholder="student@example.test" maxLength={150}/><Field name="password" label="Test password" type="password" errors={errors} autoComplete={register?'new-password':'current-password'} maxLength={128}/>{register&&<Field name="confirm" label="Confirm test password" type="password" errors={errors} autoComplete="new-password" maxLength={128}/>}<button className="btn full" disabled={busy} type="submit">{busy?'Please wait…':register?'Create demo account':'Sign in'} <Icon/></button></form><p>{register?'Already registered?':'New here?'} <a className="text-link" href={`#/${register?'login':'register'}?next=${returnTo}`}>{register?'Sign in':'Create an account'}</a></p></div></section>;}
createRoot(document.getElementById('root')).render(<App/>);
